#---------------------------Spring-----------------------------------#
spring.application.name=Portfolio-api
spring.security.user.name=tauisilva
spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.add-mappings=true

#---------------------------Swagger----------------------------------------#
springdoc.api-docs.path=/api-docs
springdoc.api-docs.version=openapi_3_1
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=swagger-ui.html
springdoc.swagger-ui.operationsSorter=Alpha
server.forward-headers-strategy=framework