#-----------------------------------------------------------------------------
# Quarkus Application Configuration
#-----------------------------------------------------------------------------
quarkus.application.name=Portfolio-api
quarkus.application.version=1.0.0
quarkus.http.port=8080

# CORS Configuration for Frontend (Angular)
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200,https://tauisilva.github.io
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS

# OpenAPI & Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.theme=monokai

mp.openapi.extensions.smallrye.info.title=Taui Silva Portfolio API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=API REST reativa em Quarkus 3 (Supersonic Subatomic Java) para o portfólio de Taui Silva
mp.openapi.extensions.smallrye.info.contact.name=Taui Silva
mp.openapi.extensions.smallrye.info.contact.url=https://github.com/tauisilva

# Health & Metrics
quarkus.smallrye-health.root-path=/q/health

# Datasource (Dev Services desativado por padrão enquanto usamos DTOs em memória)
quarkus.datasource.devservices.enabled=false
quarkus.hibernate-orm.active=false